require_relative 'objects/ball'
require_relative 'objects/box'
require_relative 'objects/door'
require_relative 'objects/enemy'
require_relative 'objects/key'
require_relative 'objects/led_panel'
require_relative 'objects/wall'
